### ISSUE TITLE
Equipo humano necesario

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#1]
Departamentos, roles y número de personas necesarias si se llevara a cabo

**Comment by dckabuki** [comment]
[empleados.docx](https://github.com/alhgo/Moksha/files/5577643/empleados.docx)

Chicos, he estado mirando los equipos que desarrollaron algunos juegos que tenemos de referencia y basándome en el de Journey he hecho la previsión de gente para el nuestro. Echadle un ojo y decidme si os sobra o falta gente.

**Comment by dckabuki** [comment]
[empleados.docx](https://github.com/alhgo/Moksha/files/5578023/empleados.docx)

He hecho algún cambio al ir recopilando las tareas que tenemos que cubrir.

**Comment by Albertossolana** [comment]
Perfecto. Lo veo bien así. Ahora con estos números de personas iré viendo el equipo que necesitaremos para cada uno de ellos y que puedan trabajar.

**Comment by dckabuki** [comment]
[empleados.docx](https://github.com/alhgo/Moksha/files/5604099/empleados.docx)

He incluído un rigger al equipo, que se me había pasado.
