### ISSUE TITLE
Material técnico

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#10]
Todas las herramientas y software necesarios para llevar el proyecto.

**Comment by Albertossolana** [comment]
[Derechos,licencias y Equípo técnicoV1.pdf](https://github.com/alhgo/Moksha/files/5578435/Derechos.licencias.y.Equipo.tecnicoV1.pdf)
He hecho un listado de los distintos softwares que usaríamos y el precio de su licencia individual. Según el número de trabajadores que seamos iré implementando el numero de licencias que necesitaremos de cada programa. También he puesto material para el estudio y un precio medio de cada uno. Echadle un vistazo y si se os ocurre alguna cosa más decirme.

**Comment by dckabuki** [comment]
¿Creéis que necesitaríamos After o algún editor de vídeo para hacer cinemáticas o post pro? 
No tengo claro si necesitaríamos ZBrush sí o sí, aunque desde luego sería conveniente. 
Y no estoy seguro de que con sólo 6 ordenadores y sillas tengamos suficientes, porque el equipo que tenemos rondaba las 20 personas.

**Comment by Albertossolana** [comment]
Tengo que modificar los números. Se necesitarán ordenadores para todos y las licencias de los programas con los que necesiten trabajar. Y sí, podríamos añadir after y premiere.

**Comment by Martix-art** [comment]
creo k el paquete adobe incluye varias licencias o a lo mejor se pueden hacer paquetes con algunos, y lo de mesas y sillas no se si la oficina viene equipada, en las fotos esta todo muy colocadito, pero no se indica

**Comment by Albertossolana** [comment]
Vale. Yo añadiría las sillas y todo porque no creo que en el local te vengan todas las que necesitamos para el equipo.

**Comment by dckabuki** [comment]
Yo incluiría también la sillas, mesas y tal. Pero eso corresponde al apartado de local y mobiliario.

**Comment by Albertossolana** [comment]
Okay. Pues Marta incluye las mesas y sillas que se necesitarán para todo el equipo que este en el estudio. Supongo que el compositor de banda sonora trabajará en el suyo propio y el QA y los testers.

**Comment by Martix-art** [comment]
Si creo k esa parte coresponde a local lo incorporare, si el otro dia hablando con oscar de si el espacio era suficiente a los departamento de banda sonora, el QA y los testers y no los incluimos, pork aunque pueden venir a enseñar algo no es necesario que trabajan desde aqui.

**Comment by Albertossolana** [comment]
[Presupuestos Cap1-5.docx](https://github.com/alhgo/Moksha/files/5602580/Presupuestos.Cap1-5.docx)
Las dos tablas de material y licencias. Esta tarde completamos los tiempos de uso de estas últimas.

**Comment by Albertossolana** [comment]
[Presupuestos Cap1-5.docx](https://github.com/alhgo/Moksha/files/5604177/Presupuestos.Cap1-5.docx)

[DAFO.pdf](https://github.com/alhgo/Moksha/files/5604184/DAFO.pdf)

Documento actualizado con lo trabajado en clase y el DAFO.
