### ISSUE TITLE
Otros

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#11]
Enlaces o fuentes desde las que se ha sacado la información.

**Comment by Martix-art** [comment]
https://www.idealista.com/inmueble/91870297/ link local

**Comment by Albertossolana** [comment]
https://www.emprendedores.es/gestion/como-se-protege-legalmente-un-videojuego/  Protección legal para nuestro videojuego.

**Comment by dckabuki** [comment]
https://www.engadget.com/the-last-campfire-review-hello-games-190059178.html desarrollo de last campfire
https://journey.fandom.com/wiki/Journey#Development_team equipo de Journey
De ambos número de empleados y tiempo de desarrollo

**Comment by dckabuki** [comment]
https://play.google.com/store/apps/details?id=com.sometimeswefly.littlealchemy&hl=es_419&gl=US
https://play.google.com/store/apps/details?id=com.habby.archero&hl=es_419&gl=US
https://play.google.com/store/apps/details?id=com.jmsc.cryptogram&hl=es_419&gl=US

Los juegos que pongo de ejemplo en el apartado de monetización

**Comment by dckabuki** [comment]
https://www.3dcube.es/hare-un-videojuego-pero-como/#Etapa_de_Pre-produccion

Información sobre las tareas por fases de producción

**Comment by Albertossolana** [comment]
https://www.indecopi.gob.pe/obras-como-lo-hago
Página para solicitar derechos de autor de obra audiovisual y software.
[GDA_creadoresProductoresDeVideojuegos.pdf]
INFO de derechos de autor en videojuegos.

**Comment by Albertossolana** [comment]
https://www.eleconomista.es/emprendedores-innova/noticias/7530245/04/16/Cuanto-tiempo-necesita-un-emprendedor-para-conseguir-financiacion.html
Financiación CEO 3-6 meses.

**Comment by dckabuki** [comment]
Chicos, estaba repasando la información de un link para la presentación y resulta que han cambiado el domino, y la información ahora está en otro sitio. El link que ya no funciona es el del desarrollo de Journey. El link nuevo es éste; https://journey-archive.fandom.com/wiki/Journey#Development_team
Como ya hemos entregado el trabajo final, por lo menos que quede reflejado aquí el cambio del link.
