### ISSUE TITLE
Plan de negocios-Flyer

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#12]
Incluye: título, logo, género, nºde jugadores, target, sinopsis, key selling points (puntos claves que facilitan la venta del juego), muestra de arte del juego, pegi provisional.

**Comment by Martix-art** [comment]
SI ME PODEIS MIRAR FALTAS SOBRE TODO AL FINAL
Moksha es un juego para dispositivos móviles en 3D de exploración y aventura para un jugador, que mezcla unas simples dinámicas para la exploración, realización de puzles y para enfrentarse a grandes enemigos, pues el juego se basa principalmente en el hecho de descubrir nuevos parajes y el uso de la no violencia. Por ello le damos la categoría de PEGI 12, puesto que, aunque el combate no muestra violencia explícita, sí hay momentos de la historia que pueden ser de mayor tono violento y dramático, aunque esto puede ser un mayor incentivo para que los padres dejen jugar a sus hijos.

**Comment by Martix-art** [comment]
Moksha es un juego para dispositivos móviles en 3D de exploración y aventura para un jugador, que mezcla unas simples dinámicas para la exploración, realización de puzles y para enfrentarse a grandes enemigos, pues el juego se basa principalmente en el hecho de descubrir nuevos parajes y el uso de la no violencia. Por ello le damos la categoría de PEGI 12, puesto que, aunque el combate no muestra violencia explícita, sí hay momentos de la historia que pueden ser de mayor tono violento y dramático, aunque esto puede ser un mayor incentivo para que los padres dejen jugar a sus hijos, al o conener violencia explicita. Por otra parte no queremos hacercar a esos fanaticos de la ciencia ficcion, mientras que buscamos jugadores interesados ademas en el arte y la cultura.

**Comment by dckabuki** [comment]
Moksha es un juego para dispositivos móviles en 3D de exploración y aventura para un jugador, que mezcla unas simples dinámicas para la exploración, realización de puzles y para enfrentarse a grandes enemigos, pues el juego se basa principalmente en el hecho de descubrir nuevos parajes y el uso de la no violencia. Por ello le damos la categoría de PEGI 12, puesto que, aunque el poco combate existente no muestra violencia explícita, sí hay momentos de la historia que pueden ser de mayor tono violento y dramático. Este hecho incluye como target potencial a familias que opinan que los videojuegos hacen violentos a sus hijos, ya que al renegar de la violencia como mecánica principal se enseña a los niños a no utilizarla también . Por otra parte queremos acercar a fans de la ciencia ficción con el apartado futurista y a otros interesados en la cultura y el arte de los pueblos que presentamos.

**Comment by Martix-art** [comment]
[flyer_01.pdf](https://github.com/alhgo/Moksha/files/5604214/flyer_01.pdf)
falta el texto de key selling points

**Comment by Martix-art** [comment]
[flyer_02.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5645083/flyer_02.pdf)
terminado
