### ISSUE TITLE
Estudio de mercado

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#13]
Debe incluir: situación del sector (según la plataforma y el contenido que ofrecemos), DAFO, USP (qué nos diferencia de la competencia)

**Comment by Albertossolana** [comment]
[DAFO.pdf](https://github.com/alhgo/Moksha/files/5604211/DAFO.pdf)

Documento DAFO.

**Comment by dckabuki** [comment]
Os paso el USP que hemos hablado en clase:

"Una aventura sin sangre. 
Y sin piel. Y sin músculo. 
Puro hueso."
