### ISSUE TITLE
Background del equipo

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#14]
Recorrido por la historia del equipo

**Comment by dckabuki** [comment]
[background_oscar.docx](https://github.com/alhgo/Moksha/files/5604261/background_oscar.docx)

Aquí tenéis mi parte del background.

**Comment by dckabuki** [comment]
![emprendimiento_oscar](https://user-images.githubusercontent.com/72690329/100377575-c73a5c00-3011-11eb-9a2c-49b22156873b.JPG)
Y mi tabla de emprendimiento.

**Comment by Martix-art** [comment]
[background_oscar.docx](https://github.com/alhgo/Moksha/files/5604302/background_oscar.docx)

**Comment by dckabuki** [comment]
[background_oscar_marta_alberto.docx](https://github.com/alhgo/Moksha/files/5604325/background_oscar_marta_alberto.docx)
Background corregido de los 3

**Comment by nomegustaprogramar** [comment]
En este archivo PDF os estoy subiendo mi background.
[Background_Alexis.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5660580/Background_Alexis.pdf)
