### ISSUE TITLE
Entrega final del plan de producción

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#15]
Entrega del plan de producción y de la presentación.

**Comment by Martix-art** [comment]
Realizado del maquetado del dosier y la presentación
[Moksha_plan_de_produccion_presupuesto_y_financiacion.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5661606/Moksha_plan_de_produccion_presupuesto_y_financiacion.pdf)
[Moksha_presentacion plan de produccion fianciacion y presupuesto.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5661608/Moksha_presentacion.plan.de.produccion.fianciacion.y.presupuesto.pdf)

**Comment by Raquel408** [comment]
PDF con workflow y equipo técnico añadido
[PLAN DE PRODUCCIÓN, PRESUPUESTO Y FINANCIACIÓN.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5665903/PLAN.DE.PRODUCCION.PRESUPUESTO.Y.FINANCIACION.pdf)
