### ISSUE TITLE
Cavar

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#17]
Necesitamos ver como generar en el mapa un agujero en el suelo, que aparezca una textura de tierra removida en ese sitio, o cualquier otra solución que pueda simular este hecho.

**Comment by alhgo** [comment]
Propuesta: que el terreno contenga el agujero hecho, y luego se importan mallas independientes que lo "tapan". Mediante programación es muy fácil eliminar esas mallas y hacer aparecer otras (por ejemplo de montones de tierra), a medida que se va cavando. Es algo rudimentario pero funcionará. ¿Al final se hará el puzzle de que cave? Eso obliga a encontrar las animaciones y añadir una pala, que es bastante complicado.

**Comment by dckabuki** [comment]
Por ahora hablamos de centrarnos únicamente en el puzzle de las estatuas que giran y en el de las luces en la niebla, pero puedo plantear el mapa con los agujeros hechos (sólo se puede cavar en zonas determinadas) y ver si después lo utilizamos.

**Comment by alhgo** [comment]
Adelante, haz los agujeros. Luego los podemos llenar de tierra sin problema :)

**Comment by Albertossolana** [comment]
Al final no realizaremos ninguna acción relacionada con este issue.
