### ISSUE TITLE
Assets Unity

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#18]
Conseguir todos los assets necesarios de la página de Unity, tanto modelo como texturas. 

- [x] Personaje
- [x] Tótems
- [x] Árboles
- [x] Piedras
- [x] Estatuas
- [x] Pedestal

**Comment by Martix-art** [comment]
Algunos elementos ya buscados

Bosque Dream Forest Tree
Hand Paind Natura Kit Lite
Space Robot Kyle 
Elemental Magic Totems

**Comment by dckabuki** [comment]
He encontrado estos assets para las estatuas y el pedestal.
El asset del gato tiene la estatua del gato y el pedestal, y el pack de estructuras japonesas una estatua de un monje, lo demás no es necesario. 
[Monje](https://assetstore.unity.com/packages/3d/oriental-structure-pack-lite-81021)
[León](https://assetstore.unity.com/packages/3d/props/exterior/hq-lion-statue-50736)
[Gato y pedestal](https://assetstore.unity.com/packages/3d/environments/historic/egyptian-tomb-cat-statue-119784)
[Guerrero](https://assetstore.unity.com/packages/3d/environments/fantasy/hand-painted-forest-lite-47738)
![estatuas](https://user-images.githubusercontent.com/72690329/104729046-237b4b80-5738-11eb-9e70-4b2d4588c04f.PNG)

**Comment by Raquel408** [comment]
Os dejo aqui los links de los assets
Low poly:
arboles
[https://assetstore.unity.com/packages/3d/vegetation/trees/low-poly-tree-pack-57866 ](url)
[https://assetstore.unity.com/packages/3d/vegetation/trees/free-trees-103208](url)
hierba
[https://assetstore.unity.com/packages/2d/textures-materials/glass/stylized-grass-texture-153153](url)
piedras
[https://assetstore.unity.com/packages/3d/environments/low-poly-rock-pack-57874](url)
[https://assetstore.unity.com/packages/3d/props/exterior/low-poly-styled-rocks-43486](url)
bosque
[https://assetstore.unity.com/packages/3d/environments/fantasy/fantasy-forest-environment-free-demo-35361](url)
totem
[https://assetstore.unity.com/packages/3d/environments/tiny-chess-stone-chess-piece-112537](url)

High Poly:
totems
[https://assetstore.unity.com/packages/3d/environments/stone-pillar-34670](url)
[https://assetstore.unity.com/packages/2d/textures-materials/brick/high-quality-bricks-walls-49581](url)
rocas
[https://assetstore.unity.com/packages/3d/props/exterior/rocks-free-pack-98219](url)
[https://assetstore.unity.com/packages/3d/props/exterior/rock-package-118182](url)
bosque
[https://assetstore.unity.com/packages/3d/environments/hand-painted-nature-kit-lite-69220](url)
[https://assetstore.unity.com/packages/3d/vegetation/trees/dream-forest-tree-105297](url)

**Comment by alhgo** [comment]
Si damos por bueno el issue, podemos pasarlo a tarjeta de cosas hechas.

**Comment by dckabuki** [comment]
Al final usaremos estos assets: 
[Árbol, hierba y piedras](https://assetstore.unity.com/packages/3d/environments/fantasy/a-piece-of-nature-40538#description)
[Cajas, señales y escombros](https://assetstore.unity.com/packages/3d/environments/lowpoly-wasteland-props-138348)
Pero quizá nos vendría bien tener algún árbol de otra variedad para ir variando entre ellos.

**Comment by Raquel408** [comment]
dejo aqui los assets de los animales, algunas no tienen texturas
[Elefante 1](https://free3d.com/es/modelo-3d/elephant-v1--87133.html)
[Serpiente](https://free3d.com/es/modelo-3d/a-snake-with-wings-v1--377729.html)
[Delfin](https://free3d.com/es/modelo-3d/-dolphin-v1--12175.html)
[Aguila1](https://free3d.com/es/modelo-3d/eagle-3-42527.html)
[Aguila 2](https://free3d.com/es/modelo-3d/eagle-v1--658406.html)
