### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#20]
Algo más detallado para realizar un seguimiento. Tareas a realizar:

- [x] Elaborar las imágenes necesarias para el interfaz (tanto para los menús como para el HUD). Muy importante tener en cuenta las animaciones
- [x] Diseñar un mapa de navegación: páginas, botones, interacción...
- [x] Diseñar la interactividad (qué botones activarán qué menús)
- [x] Crear las escenas necesarias siguiendo el mapa de navegación e incorporar los canvas para la UI
- [x] Crear la interactividad mediante programación
- [x] Añadir ventana de carga
- [x] Interfaz Inicio
- [x] Interfar Pausa
- [x] Interfaz Controles
- [x] Interfaz Movimiento (objetos que salen con las herramientas)

**Comment by Martix-art** [comment]
Subidos png para hacer la interfaz

**Comment by Martix-art** [comment]
Subido boceto mapa de navegacion

**Comment by Albertossolana** [comment]
Videotutorial para hacer un menú principal en Unity:
https://www.youtube.com/watch?v=c2bifOsx0QA

**Comment by alhgo** [comment]
Miro los bocetos. En cuanto al vídeo, efectivamente, el SceneManager era lo que quería que viésemos ya la semana que viene, así que contad con ello.

**Comment by Martix-art** [comment]
Hecha interfaz de inicio

**Comment by Martix-art** [comment]
- [ ] Interaz Inicio
- [ ] Interzar Pausa
- [ ] Interfaz Controles
- [ ] Interfaz Movimiento
- [ ] Interfaz Pantalla Carga

**Comment by alhgo** [comment]
Ya he visto el menú de entrada. Tal y como hablamos, propongo crear un sistema de partículas que simule estrellas tintineando sobre un fondo. ¿Es posible conseguir ese fondo que habéis usado sin las estrellas? En este vídeo se muestra más o menos cómo se hacen estrellas mediante sistema de partículas (aunque lo veremos más adelante en clase): https://www.youtube.com/watch?v=UHCwUMJOFsc
Si nos gusta, lo podemos usar también en el menú de controles.
¿Cómo van los menús del HUD? Hay un issue para eso? Esos los tendremos que animar

**Comment by Martix-art** [comment]
¿Es posible conseguir ese fondo que habéis usado sin las estrellas? 

-No creo la foto es asi no habia mas opciones

¿Cómo van los menús del HUD? Hay un issue para eso?

-Eso tequeria preguntar yo tengo los sptir dibididos y preparados pero no tengo ni idea de como hacerlo, creo que no hay issue de esa parte

**Comment by Martix-art** [comment]
[panta de carga](https://youtu.be/mYOKFOlnbRg)

**Comment by Martix-art** [comment]
pantalla de controles, el unico boton que hay no funciona @alhgo

**Comment by Martix-art** [comment]
He estado trabajando intentando meter las particular en la pantalla inicial, pero no hay forma, las particulas estan ahi, pero cuando estas en vista 2d y en game no se ven, solo se ven si estas en 3d.

No se si me estos saltando activar algo, @alhgo.

Tambien he visto otros videos por si no lo estaba haciendo bien.
https://youtu.be/oPUxv-zClNA
https://youtu.be/v_z2X9QjqsE

**Comment by alhgo** [comment]
Vale, te comento los errores porque efectivamente era una tontería (pero difícil de detectar), a ver si los podemos resolver que la cosa está quedando muy chula:
1. El botón del menú de controles no funciona porque se ha borrado el elemento "EventSystem" que se crea cada vez que se inserta un canvas (fallo mío, os debí comentar que eso lo necesita Unity para controlar la interactividad de los botones). Si creas un nuevo canvas, vacío, se creará de nuevo ese elemento y todo volverá a funcionar (incluso puedes borrar el canvas vacío)
2. En cuanto al sistema de partículas no se vé por dos motivos: el primero, que la cámara no está apuntando al lugar donde tienes las partículas (aunque veas el menú en la cámara, no es porque esté apuntando a él, sino porque lo tienes en modo de Scree Space Overlay, y de esa forma siempre cubre la cámara), y es es el segundo motivo, al tenerlo en "Overlay" todo lo que hay en el menú "tapa" la escena (si quitas la imagen de fondo verás las estrellas). Solucción, pon el menú en modo "Scree Space Camera" y podrás organizar los elementos del menú en perspectiva, como si fuesen elementos más de la escena, poniendo las estrellas entre los botones y el fondo

**Comment by Martix-art** [comment]
-La primera correcion ya esta correguida, muchas gracias, cierto era una tonteria lo debi borrar sin querer.
-El punto dos nada, lo he cambiado a scree space camera, y he apuntado corectamente con la camara, pero nada. Si que es verdad que si quito el canvas si se ve, pero si esta activado no se ven, ademas los he organizado en perspectiva (botones primero, efecto estrellas y el fondo), espero que me lo puedas volver a mirar @alhgo

**Comment by alhgo** [comment]
Lo estoy mirando, y veo una organización extraña de los elementos del canvas, lo que hace que sea imposible moverlos de forma independiente. Casi prefiero crear uno nuevo desde cero y ver qué está pasando, si es posible contigo delante (o compartiendo pantalla en remoto)

**Comment by Martix-art** [comment]
Okey, si mejor verlo.
Ahora mismo estamos en clase con Maria. Mañana las primeras horas tenemos con Maria y luego contigo. 
Yo si hiciese falta por la mañana podria

**Comment by alhgo** [comment]
Yo por la mañana imposible. Durante las horas de clase buscamos un hueco. Si lo hacemos por el aula virtual, otros podrán ver cómo lo resolvemos que seguro que les resulta útil

**Comment by Martix-art** [comment]
Pues me conecto en tus horas.

**Comment by Martix-art** [comment]
@alhgo a la hora de desplazarnos por el menu  de inicio o el de pausa, tenemos que hacerlo con los controles del mando?
y muchas gracias, el efecto de estrellas ya esta arreglado

**Comment by alhgo** [comment]
Este es el código para la pantalla de carga (la corrutina):

```
IEnumerator CargarAsync(int NumeroDeEscena)
    {
        //AsyncOperation Operacion = SceneManager.LoadSceneAsync(NumeroDeEscena);

        PantallaDeCarga.SetActive(true);

        float Progreso = 0f;

        while (Progreso <= 1)
        {

            Slider.value = Progreso;
            Progreso +=0.01f;

            if(Progreso > 0.99)
            {
                SceneManager.LoadSceneAsync(NumeroDeEscena);
               
            }
            

            yield return null;

        }

        /*
        while (!Operacion.isDone)
        {
            float Progreso = Mathf.Clamp01(Operacion.progress / .9f);
            Slider.value = Progreso;

            yield return null;
        }

        */

    }
```

**Comment by alhgo** [comment]
Acabo de hacer un commit con unas pruebas de menú animado, en la escena de Pruebas de Scripts. Comento:
- He creado varias animaciones y un Animator vinculado al Canvas, que hacen aparecer y desaparecer los botones (no sé si era esa la animación que se quería, pero se puede cambiar). He retocado los botones con Photoshop para que tengan varios estados, eso se puede cambiar también.
- El disparador del trigger es la barra espaciadora porque no he querido tocar la configuración de Input del proyecto (falta añadir un "nombre" para el botón "Y"
- De momento para navegar por los botones se tendrá que hacer con el ratón ya que el joystick está vinculado al robot, ya veríamos cómo cambiarlo en el futuro si acaso
- He creado un prefab y un material nuevo, para simular una escafandra, que he metido como hijo del robot (dependiente de su cabeza para que se mueva con ella). Al pulsar el botón de la burbuja se activa
- Todo está en el script que he creado para ello.

Si nos gusta, lo podemos trasladar a la escena principal y dar el tema por cerrado

**Comment by dckabuki** [comment]
Acabo de echarle un ojo y es justo lo que nos habíamos imaginado. En cuando podamos le asignaremos un imput para controlarlo con el mando. Muchas gracias @alhgo

**Comment by Martix-art** [comment]
si esta perfecto
