### ISSUE TITLE
Modelado de terrenos

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#21]
- [x] Investigar en Unity la formación de terrenos.
- [x] Modelar la base del terreno (elevaciones)
- [x] Texturizar terreno
- [x] Añadir detalles

**Comment by alhgo** [comment]
Importante: como es muy probable que los terrenos se modifiquen constantemente, para que no haya conflictos con otros commits, te sugiero que crees una escena solo para terrenos (luego la podremos borrar) y cuando demos con el terreno definitivo ya lo llevaremos a la escena correspondiente, aunque sea haciendo un Prefab con todo el terreno.

**Comment by dckabuki** [comment]
Con los vídeos y lo que he mirado estas vacaciones he estado haciendo pruebas de terreno.
Intentaré tener mañana por lo menos la base del terreno.

**Comment by alhgo** [comment]
En cuanto pueda intentaré crear un prefab de un terreno en una escena para ver si se puede importar en otra escena sin problema (en teoría sí), incluyendo árboles, detalles, etc. Si alguien lo prueba antes y ve que funciona, que lo confirme por aquí

**Comment by alhgo** [comment]
Este issue lo tenía pendiente. He probado a crear un Empty Object y meter dentro todo lo de una escena menos las luces y la cámara: terrenos, props, personajes, etc. Y he hecho un prefab con todo. Luego me lo he llevado a otra escena, y parece que funciona
