### ISSUE TITLE
Programación

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#22]
Plantear las distintas acciones que se tendrán que llevar a cabo mediante programación. 
-Interactividad del mando y movimiento del personaje.
-Movimiento las estatuas.
-Encendido y apagado de las luces en la niebla.
-Interactividad de la interfaz.

**Comment by alhgo** [comment]
Consejo: no crear Issues tan genéricos, porque en este caso es difícil hacer un seguimiento. Cada uno de los apartados que aparecen ahí casi corresponden a un issue en sí mismo, que deberán abordarse en cada momento. Yo daría por cerrado este y abriría por ejemplo uno dedicado solo a la interactividad el mando, que deberá coordinarse con la animación del personaje
