### ISSUE TITLE
Programación: movimiento de las estatuas 

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#25]
Tendremos un puzle que consista en girar unas estatuas (en torno al eje y) para que miren a determinadas direcciones (siguiendo unas instrucciones en un pedestal). Una vez todas las estatuas estén en posición correcta, aparecerá un tótem como recompensa. 

- [x] Cómo se van a girar las estatuas (script)
- [x] Cómo comprobar la dirección correcta 
- [x] Cómo hacer que aparezca la recompensa
- [x] Cómo se va a interactuar con las estatuas

**Comment by alhgo** [comment]
Si no recuerdo mal, las estatuas se componían de varias partes que rotaban en dos direcciones (CC y CW) de forma independiente, hasta formar dibujos, ¿correcto? Si es así:

- [x] Estaría bien tener un boceto en el repositorio
- [x] Hay que modelarlas y texturizarlas (no es necesario gran detalle, y el relieve se puede dar con un mapa de normales)
- [x] La interactividad la haría directamente creando un método a cada parte de la columna que modigica su giro (podemos usar el sistema Euler para girar). 
- [ ] En cuanto a programación, sencillo: como el funcionamiento de una llave: cada columna tiene un booleano que es true cuando está en posición correcta, y un método comprueba en todo momento mediante un bucle en un array si todas están correctas o no, lo cual a su vez activa o desactiva otro booleano

**Comment by dckabuki** [comment]
Las estatuas se girarán por cuartos en una única dirección, pulsado en botón de interacción.

**Comment by alhgo** [comment]
Ok. La verdad es que podemos hacerlo por código o creando animaciones en el panel de Animation (4 animaciones una por cada cuarto) y creando transiciones en el Animator Controller. En cuanto tengamos el modelo en 3D podemos empezar a hacer pruebas. ¿quién se encarga de hacer el modelo y darle la textura?

**Comment by dckabuki** [comment]
Estábamos pensando en utilizar assets para las estatuas, pero creo que todavía no están. 
Como queremos que el puzzle consista en que las estatuas miren a una dirección determinada, necesitaríamos estatuas con una cara distinta o aspecto humano/animal. En caso de no encontrar esos assets, intentaríamos texturizar como piedra modelos de animales o personajes. 
Sobre cómo moverlas...lo tenemos que hablar y decidir.

**Comment by Albertossolana** [comment]
@alhgo Ya está en la escena del mapa el personaje (con su movimiento e interacciones) y el puzzle de las estatuas. Para que le eches un vistazo.
