### ISSUE TITLE
Animar las luces del puzzle de la niebla

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#29]
Necesitaríamos hacer un ciclo de animación para las luces del puzzle.
Sería muy simple, únicamente hacia arriba y hacia abajo, como si estuviera levitando.

- [ ] Crear la animación de levitación
- [ ] Aplicar la animación al objeto de la luz

**Comment by alhgo** [comment]
Os recuerdo que al ser varias luces, lo que tenemos que hacer es un prefab, ya que entiendo que todas se comportan igual, verdad? Importante, para que no os volváis locos. Cread un empty object en coordenada 0.0.0, y poner la luz como hijo en esas coordenadas también, y haced la animación a la luz (no al empty object). Eso os permitirá mover luego el objeto padre a la ubicación definitiva, ya que al haber animado posiciones, la luz tenderá a ir a las coordenadas que le habéis dado en la animación

**Comment by Albertossolana** [comment]
Vamos a usar un sistema de partículas en vez de una luz. Por lo que este issue no será necesario. Hablaremos de este tema en el issue de la niebla.
