### ISSUE TITLE
Lista de tareas a realizar 

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#3]

**Comment by dckabuki** [comment]
[tareas.docx](https://github.com/alhgo/Moksha/files/5578028/tareas.docx)

De momento está recogido lo que hace cada rol. ¿Habrá que incluir el plan de producción como tarea a elaborar?

**Comment by dckabuki** [comment]
[tareas.docx](https://github.com/alhgo/Moksha/files/5578041/tareas.docx)

He incluido las tareas que realiza cada departamento. ¿Habrá que incluir el propio plan de producción como tarea? ¿Deberíamos incluir cosas como "ir a ferias de juegos", "reuniones con expertos" etc?

**Comment by Martix-art** [comment]
Lo he mirado y yo creo que esta bien, lo que preguntas de ir a ferias y eso creo que esta implicito dentro de las tareas del CEO o del productor ejecutivo, pero si no el proximo dia lo preguntamos

**Comment by Albertossolana** [comment]
Yo creo que con esa explicación perfecto.

**Comment by dckabuki** [comment]
[tareas.docx](https://github.com/alhgo/Moksha/files/5604102/tareas.docx)
[tareas_fase.docx](https://github.com/alhgo/Moksha/files/5604103/tareas_fase.docx)
Incluyo dos archivos, uno con las tareas organizadas por fase y otra en la que detallo más lo que hará cada departamento.
