### ISSUE TITLE
¿Cómo entramos al juego?

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#32]
Cuando pulsamos el botón de "play", ¿qué pasa?

- [x] Definir cómo pasamos del menú inicial al juego (¿Fundidos? ¿Pantalla de carga?)
- [x] Cómo pasar de la escena del menú a la escena del juego

**Comment by Martix-art** [comment]
[pantalla de carga](https://youtu.be/mYOKFOlnbRg), posible solucion

**Comment by Martix-art** [comment]
![logo_sin_fondo](https://user-images.githubusercontent.com/72756317/105577532-8beeac00-5d7a-11eb-9598-4f1eba83c20b.png)

**Comment by Martix-art** [comment]
![pantalla carga](https://user-images.githubusercontent.com/72756317/105577571-c7897600-5d7a-11eb-8393-d54b4a650118.PNG)

**Comment by Martix-art** [comment]
Pantalla de carga y script realizados, ningun fallo

**Comment by alhgo** [comment]
Hola. Hay cosas en el menú de inicio que no funcionan correctamente, y no sé muy bien por qué. Si ponemos una pantalla de carga, podemos hacerlo en una escena diferente y así animamos la barra (me encargaría yo) Le daría un toque muy elegante

**Comment by Martix-art** [comment]
Debe dar fallo pork me puse a tocar lo del efecto pero funcionba, la ultima vez que lo comprobe
