### ISSUE TITLE
Ilustración mapa

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#36]
Necesitamos una ilustración que sea todo el mapa del nivel en el que nos encontramos.

**Comment by Martix-art** [comment]
mapa top real de la zona
![mapa de navegacion](https://user-images.githubusercontent.com/72756317/108338629-c3644300-71d6-11eb-9d5e-c4318d65423e.PNG)

**Comment by Martix-art** [comment]
mapa top para hacer la ilustracion lo mas parecida
![mapa](https://user-images.githubusercontent.com/72756317/108338694-d840d680-71d6-11eb-82f1-535b42649475.PNG)

**Comment by Martix-art** [comment]
mapa convertido a ilustraccion
![mapa moksha](https://user-images.githubusercontent.com/72756317/108338782-edb60080-71d6-11eb-8999-ea19ea9eed6a.png)

**Comment by Martix-art** [comment]
crear pantalla con la estetita de moskha
![mapa](https://user-images.githubusercontent.com/72756317/108338866-06beb180-71d7-11eb-84e9-ea2bafc95e17.png)

**Comment by Martix-art** [comment]
mapa con nombres de las diferentes zonas, y con nombres de resto de planetas, adeas de una rosa de los viento, para ayudar con el puzzle de las estatuas
![mapa_02](https://user-images.githubusercontent.com/72756317/108603558-f827f400-73a8-11eb-94da-10ca5dfabab5.png)
