### ISSUE TITLE
Problema de colisiones con los objetos del terreno

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#37]
Hemos empezado las pruebas de control del personaje por el terreno, el problema es que el personaje no colisiona con los objetos colocados con el pincel de detalles (piedras y columnas). 
Hay que investigar si se puede solucionar, convertir a pincel de árboles (que sí colisionan) o si hace falta quitarlo y empezar de cero.

**Comment by dckabuki** [comment]
Por ahora no he encontrado ninguna solución. 
He intentando ponerle al terreno un mesh collider y asociar los prefab de las rocas y poner un collider al propio prefab, pero sigue sin funcionar.

**Comment by alhgo** [comment]
Los detalles que se ponen al terreno por defecto no incluyen colisonadores (imagínate las briznas de hierba con colisionador). Si incluyen rocas tan grandes que sí que lo requieren, creo que hay 2 opciones: o ir una por una añadiendo objetos 3D con colisionador pero sin el renderizado activado para que estén donde queremos que la roca impida pasar al personaje, o añadir las rocas como árboles, no como detalles (ya que los árboles sí tienen colisionador)

**Comment by dckabuki** [comment]
Entonces casi mejor que los quite y los vuelva a hacer con el pincel de árboles.
Gracias.
