### ISSUE TITLE
Guión con Twine 

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#39]
Hay que adaptar una parte de la historia del juego con Twine.

**Comment by dckabuki** [comment]
Ya está listo el twine de la historia. Cubre lo que hablamos, la historia de todo el primer mundo. Echadle un ojo y me decís.
(Github no aceptaba el archivo en html, por eso está comprimido)

[Moksha_el_inicio.zip](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/6061406/Moksha_el_inicio.zip)

**Comment by Martix-art** [comment]
esta genial, muy muy logrado y con muchisimos detalles, de los que hemos ido hablado mientras los diseñabamos
