### ISSUE TITLE
Flujo de trabajo 

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#4]
Workflow más adecuado para el proyecto

**Comment by Raquel408** [comment]
Nuevo Workflow
 
[Flujo de Trabajo.docx](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5661757/Flujo.de.Trabajo.docx)
[Flujo de Trabajo.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5661770/Flujo.de.Trabajo.pdf)

**Comment by Martix-art** [comment]
Heee no se si esta correcto no entiendo exactamente que hay k poner el worflow, tenemos k preguntar a victor, pork a mi me parece k es como un diagrama de gantt pero redactado y no estoy tampoco segura de eso

**Comment by dckabuki** [comment]
Yo tampoco lo tengo claro, mañana preguntamos. En cualquier caso, en la lista de tareas que subí el otro día hay más tareas a realizar que no se reflejan en el workflow.
