### ISSUE TITLE
Biblia de Arte

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#40]
Hay que realizar la biblia de arte con bocetos y concepts, además de capturas de la versión definitiva.

**Comment by Martix-art** [comment]
documento de la biblia de arte, no he incluido todas las imagenes las pondre en el documento final

[biblia de arte.docx](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/6061051/biblia.de.arte.docx)

**Comment by dckabuki** [comment]
He corregido la biblia de arte. Hay algún cambio de frases que me han parecido difíciles de entender, pero la base es la misma. 
[biblia_de_arte_corregida.docx](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/6061572/biblia_de_arte_corregida.docx)
