### ISSUE TITLE
PDF 

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#45]
Necesitamos colocar toda la información del proyecto en un pdf.

**Comment by Martix-art** [comment]
[Moksha_trabajo_final.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/6082526/Moksha_trabajo_final.pdf)

**Comment by Martix-art** [comment]
con correciones
[Moksha_trabajo_final_01.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/6082759/Moksha_trabajo_final_01.pdf)
