### ISSUE TITLE
Presentación 

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#46]
Necesitamos plasmar la información del pdf en una presentación.

**Comment by Martix-art** [comment]
patilla presentacion oral

![pantilla](https://user-images.githubusercontent.com/72756317/108604432-38d63c00-73ae-11eb-9fe9-01ef288e0c0c.png)

**Comment by Martix-art** [comment]
[moksha_presentacion.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/6085873/moksha_presentacion.pdf)
