### ISSUE TITLE
Pausar el juego

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#49]
Necesitamos saber cómo volver al punto exacto en el que estábamos en el momento en que le dimos al botón de pausa.

**Comment by Albertossolana** [comment]
@alhgo hemos dado con el problema de pausar el juego mientras nos encontramos en otra escena. ¿Hay alguna forma de volver a la escena de juego justo en el mismo punto donde la dejamos? ¿O deberíamos poner estos menús dentro de la escena en un canvas?

**Comment by alhgo** [comment]
Yo creo que es mejor meter los canvas en la misma escena, y sencillamente hacerlos visibles. ¿Cómo resolvisteis lo de la pausa? ¿Dónde puedo ver el script? Por cierto, hay un comando en Unity que pone en pausa la ejecución de todos los scripts, que es poniendo el tiempo en 0, y por tanto pausando el juego: `Time. timeScale = 0`

**Comment by Martix-art** [comment]
@alhgo 
Hemos metido los canvas de menu de pausa, menu controles y menu mapa (solo estos tienen que tener el componente Time. timeScale), los dos primeros se siguen relacionando los botones con las escenas aun no hemos metido la opcion de parar el tiempo. 
Hemos estado probando en el menu de mapa que cuando entres este desactivado, y al pulsar un boton se active el canvas y se pare el juego, no lo hemos conseguido y no nos hemos querido meter ha hacer los otros dos hasta que este no funcione.
Si conseguimos que el tiempo se pare, pero no activa y desactiva el canvas cuando le damos al boton.

A ver si mañana nos puedes echar un vistazo a esto.

Este scirpt esta asociado a el canvas de mapa (Menu_Mapa), por si puedes echarle un vistazo.

**Comment by alhgo** [comment]
A ver si puedo echar un vistazo hoy (quería mirar también lo de menús animados). Pero siempre hay que tener en cuenta que pausar el juego con el TimeScale es peligroso, ya que impide que se ejecute cualquier otro script. Los menús siguien funcionando porque ya se han cargado, pero otros scripts no. Una opción es que la función que ejecuten vuelvan a poner el TimeScale a 1, hacen lo que tengan que hacer, y lo vuelvan a pausar. Veremos a ver.
