### ISSUE TITLE
Diagrama de Gantt

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#5]
Cronograma de producción completo

**Comment by Martix-art** [comment]
Debido a que la tarea de Flujo de trabajo a fecha de hoy no está aún acabada, he llevado a cabo una aproximación y el orden de ejecución de las tareas a realizar durante los dos años de desarrollo del videojuego.

[MOKSHA_01.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5645919/MOKSHA_01.pdf)

Si alguno cree que hay alguna fecha un poco rara o inesacta que me informe
