### ISSUE TITLE
Ultimas tareas

### ISSUE THREAD

**Issue by Martix-art** [CIFP-Jose-luis-Garci/Moksha#50]
- [x] Canvas instrucciones estatuas
- [x] Solución agachado (después no se puede pasar a correr)
- [ ] Solucionar giro doble de las estatuas NO SE VA A ARREGLAR
- [x] Aparecer/recoger totems (puzzle luces)
- [x] Aparecer/recoger totems (puzzle estatuas)
- [x] Meter menú de herramientas
- - [x] abrir menú
- - [x] navegar entre las herramientas
- - [x] seleccionar herramienta
- [x] Bakear luces
- [x] Elegir posición de inicio
- [x] Activar menú del mapa y que el juego se pause
- [x] Hacer lo mismo con el resto de los canvas que requieran esta función de pausa
- [x] Bajar parametro de la niebla para poder salir
- [ ] Sonido que cambie dependiendo del lugar

**Comment by Martix-art** [comment]
@alhgo hemos creado un canvas que se active cuando pulsamos un boton dentro de una colision, pero no hemos sido capaces de activar el canvas.

**Comment by alhgo** [comment]
Acabo de subir el script que hace que se desvanezca la niebla al coger el tótem. Está vinculado al prefab de la niebla. Eso sí, para poder "leer" si se ha cogido el tótem, he tenido que modificar el script "cogerTotem.cs", crando una booleana que pasa a true al cogerlo y que se lee desde el prefab de la niebla. Si tenéis que modificar ese script, sincronizarlo primero

**Comment by Albertossolana** [comment]
@alhgo ¿Dónde has subido el script? No nos sale ningún commit nuevo en Git.

**Comment by alhgo** [comment]
Sorry, que todavía no había hecho el push (qué rapidos) Acabo de hacer dos, ese y otro con el que podréis navegar por el menú de herramientas usando las flechas del GamePad.
IMPORTANTE: como no he querido sincronizar la escena, tendréis que seleccionar el "InitMenu" y arrastrar los botones de las herramientas al array que he creado en el script (en el orden que aparecen en el menú, de izquierda a derecha)

**Comment by Albertossolana** [comment]
Gracias @alhgo, ya se lo he aplicado y funciona.
