### ISSUE TITLE
Equipo técnico

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#6]
Salario y gastos en el equipo.

**Comment by Raquel408** [comment]
Aquí os dejo el pdf del equipo tecnico y humanos
[Equipo humano y tecnico (GDD).pdf](https://github.com/alhgo/Moksha/files/5626134/Equipo.humano.y.tecnico.GDD.pdf)

**Comment by Raquel408** [comment]
este es el nuevo documento
[Equipo técnico.docx](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5661135/Equipo.tecnico.docx)
[Equipo técnico.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5661137/Equipo.tecnico.pdf)

**Comment by Albertossolana** [comment]
Raquel, el listado de los trabajadores ya se encargó Óscar de hacerlo en la tarea de equipo humano necesario. Lo que hay que hacer aquí es coger esa lista de todos los trabajadores que habrá y ver lo que hay que pagarle a cada uno de ellos.

**Comment by Albertossolana** [comment]
Tienes que hacer un presupuesto de los gastos que tendremos en el equipo. Si quieres mira el mío de los presupuestos para las licencias de software o material, o el de marta del mobiliario.
