### ISSUE TITLE
Fuentes de financiación principales

### ISSUE THREAD

**Issue by dckabuki** [CIFP-Jose-luis-Garci/Moksha#7]
¿De dónde vamos a sacar el dinero? 
Mirar las fuentes de la presentación

**Comment by nomegustaprogramar** [comment]
Estos son los métodos de financiación principales para Moksha.
[Fuentes de Financiación Principales.pdf](https://github.com/CIFP-Jose-luis-Garci/Moksha/files/5660541/Fuentes.de.Financiacion.Principales.pdf)
