### ISSUE TITLE
Local y mobiliario

### ISSUE THREAD

**Issue by Albertossolana** [CIFP-Jose-luis-Garci/Moksha#8]
Encontrar la localización y la cantidad de dinero para destinar.

**Comment by Martix-art** [comment]
Posible local, con muy buen espacio y un precio razonable https://www.idealista.com/inmueble/91848837/foto/1/

**Comment by Martix-art** [comment]
Perdón el de antes me confundi era solo para alquilar despachos.
Pero he encontrado otro https://www.idealista.com/inmueble/91870297/ que cumple con muchas de las cosas que nosotros pedimos.

**Comment by Albertossolana** [comment]
Me mola. Tiene varios espacios según la descripción  así que perfecto para todas las tareas que realicemos.

**Comment by dckabuki** [comment]
Creo de espacio va bien para las personas que necesitaríamos.

**Comment by Martix-art** [comment]
[local y mobiliario.docx](https://github.com/alhgo/Moksha/files/5580205/local.y.mobiliario.docx)
he estado escribiendo las caracteristicas del local y de la zona. Tambien he creado el mapa del plano real de la zona. Si me podeis revisar los textos, please

**Comment by dckabuki** [comment]
[local.y.mobiliario.docx](https://github.com/alhgo/Moksha/files/5582223/local.y.mobiliario.docx)

He corregido faltas y cambiado la redacción de algunas frases para que se entienda mejor. Por lo demás, todo bien.

**Comment by Martix-art** [comment]
Okey gracias

**Comment by Martix-art** [comment]
He estado haciendo el plano del local y colocando las mesas y hay puestos para 15 personas, podriamos llegar hasta los 17 se fuera necesario

**Comment by Martix-art** [comment]
[local.y.mobiliario.docx](https://github.com/alhgo/Moksha/files/5588591/local.y.mobiliario.docx)
creo que con esto ya estaria la parte de local y mobiliario, echarle un ojo cuando podais

**Comment by dckabuki** [comment]
[local.y.mobiliario.docx](https://github.com/alhgo/Moksha/files/5588941/local.y.mobiliario.docx)

Ya está corregido. Yo lo veo bien, pero, ¿el precio de los muebles es por unidad o en total? Deberías ponerlo. Creo que también harían falta cosas como armarios y ficheros para almacenar documentos y cosas como las tabletas gráficas y demás. Y como es del apartado de presupuestos yo añadiría al final el coste total de todo el mobiliario.

**Comment by Martix-art** [comment]
le preguntare si hace falta ser tan detallados con el mobiliario, pork esas cosas no son mobiliario es material de oficina. Y lo de presupuesto si puedo poner el total

**Comment by Martix-art** [comment]
[local.y.mobiliario.docx](https://github.com/alhgo/Moksha/files/5595971/local.y.mobiliario.docx)
vale ya estan los cambios que me habeis pedido, he pedido un apartado de presupuesto con una tabla con toda la informacion, es  como las que nos pone el en el temario, deberiamos hacerlas todos igual  o lo mas parecidas. Oscar le he preguntado lo de si meter los archivdores, como aun no me ha contestado, siempre estoy a tiempo de quitarlo

**Comment by Albertossolana** [comment]
Genial Marta. para mañana tendré el documento de licencias con la tabla y los precios totales.

**Comment by dckabuki** [comment]
Yo lo veo perfecto como está, si hay que hacer cambios los hacemos a posteriori.
